name: import_whatsapp_chat
description: A flutter plugin that enables flutter apps to receive exported chats from WhatsApp.
version: 1.0.23

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  path_provider: ^2.0.11
  collection: 1.19.0
  flutter_archive: ^6.0.3
  share_handler: ^0.0.22
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.whatsapp.import_whatsapp_chat
        pluginClass: ReceiveWhatsappChatPlugin
      ios:
        pluginClass: ReceiveWhatsappChatPlugin

